# Computational Neuroscience course

3rd session (Friday, April 23 2021): 
- Introduction to the modeling of realistic spiking neural networks by showing how to 
    - 1/ use a remote computational facility 
    - 2/ follow simple tutorials to model a spiking neural net 
    - 3/ apply this knowledge to a real-world use case
    
    
- Morning (Alberto, alberto.vergani@univ-amu.fr) : 
  - 9:00 - 12:30, introduction to simulating spiking neuronal networks by applying the theory on the eBrains platform
  

- Afternoon (Laurent, laurent.perrinet@univ.amu.fr) : 
  - 14:00 - 17:30, a practical application for the replication of a neurophysiological study 
  [[link]](https://github.com/CONECT-INT/2021-04-23_PhDProgram-course-in-computational-neurosciences)

# EBRAINS Neuromorphic services and HBP

- Ebrains https://ebrains.eu/ and the The Human Brain Project https://www.humanbrainproject.eu/en/
- In particular, see https://ebrains.eu/service/neuromorphic-computing/

- Digital computation / Simulation / SpiNNaker / neurons are software
- Analog computation / Emulation / BrainScales / neurons are hardware
    

## machine resources

- BrainScaleS
     - Kirchhoff Institut Für Physik, Heidelberg University, DE
     - physical (analogue or mixed-signal) emulations of neuron, synapse and plasticity models 
     - digital connectivity
     - ten thousand times faster than real time
     - access with https://wiki.ebrains.eu/bin/view/Collabs/neuromorphic/BrainScaleS/

<img align="center"      
     src="https://electronicvisions.github.io/hbp-sp9-guidebook/_images/6D_0073294_Racks_19WaferSystemsInstalled_30March2016_cropped_1000px.jpg" width="500" height="500" />

- SpiNNaker 
    - School of Computer Science, University of Manchester, UK
    - SpiNNaker (Spiking Neural Network Architecture) is a massively parallel manycore supercomputer 
    - numerical models running in real time on custom digital multicore chips
    - using the ARM architecture https://www.youtube.com/watch?v=EhPpxsK2Ia0
    - access with https://wiki.ebrains.eu/bin/view/Collabs/neuromorphic/SpiNNaker/

<img align="center"        
 src="https://www.zdnet.fr/i/edit/ne/2019/01/spinnaker-at-univ-manchester.jpg" width="500" height="500" />


# More info about SpiNNaker

- Jupyter Lab login at https://spinn-20.cs.man.ac.uk/hub/home

- It's composed of 57,600 processing nodes, each with 18 ARM9 processors and 128 MB of mobile DDR SDRAM, totalling 1,036,800 cores and over 7 TB of RAM

- The completed design is housed in 10 19-inch racks, with each rack holding over 100,000 cores

- Each core simulates 1,000 neurons (the goal is to simulate up to a billion neurons in real time)

- SpiNNaker requires about 100 kW from a 240 V supply and an air-conditioned environment

- SpiNNaker the hardware http://apt.cs.manchester.ac.uk/projects/SpiNNaker/

- sPyNNaker the software https://www.frontiersin.org/articles/10.3389/fnins.2018.00816/full

- Supported features http://spinnakermanchester.github.io/spynnaker/4.0.0/SPyNNakerLimitations.html
    
- PDF document https://spynnaker.readthedocs.io/_/downloads/en/latest/pdf/

- PDF short induction http://spinnakermanchester.github.io/spynnaker/4.0.0/RunningPyNNSimulationsonSpiNNaker-LabManual.pdf

- SpiNNaker mailing list google https://groups.google.com/g/spinnakerusers?pli=1

- Youtube video https://www.youtube.com/watch?v=V3MlOAru6Qk

- comparison among SpiNNaker and NEST with HPC,  van Albada et al 2018 https://www.frontiersin.org/articles/10.3389/fnins.2018.00291/full

> With approximately 80, 000 neurons and 0.3 billion synapses, this model is the largest simulated on SpiNNaker to date. (...) Comparison with simulations using the NEST software on a high-performance cluster shows that both simulators can reach a similar accuracy, despite the fixed-point arithmetic of SpiNNaker, demonstrating the usability of SpiNNaker for computational neuroscience applications with biological time scales and large network size.

# Info about PyNN 

![](https://neuralensemble.org/static/photos/pynn_logo.png)

- A Python package for simulator-independent specification of neuronal network models

- PyNN works with multiple simulators (SpiNNaker, NEST, Brain, Neuron, etc)

- If you want to install install PyNN on your local machine, see info http://neuralensemble.org/docs/PyNN/installation.html

- Paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2634533/

- PyNN website http://neuralensemble.org/docs/PyNN/index.html

- PyNN mailing list https://groups.google.com/g/neuralensemble



# Goal of this tutorial on PyNN

- Learn code elements to run a Spiking Neural Networks (SNNs) by using PyNN on the SpiNNaker neuromorphic system.


## knowledge assumptions: 

- basis of spiking neural network theory (https://neuronaldynamics.epfl.ch/online/index.html)
- familiarity with physical quatities related to electric circuits (e.g., voltages, conductances, currents, capacitances, etc)
- basic python coding (numpy, work with dictionaries, some matplotlib tools, etc)

# Content:

## network building and running [block1, 9:15-9:50, than break]
1. neurons
    - cell types
    - populations
    - recording variables
    
    
2. connections
    - synapse types
    - connections types
    - projections


3. simulation managing
    - computational settings
    - save and load outputs
    - visualization tools

## network examples [block2, 10:00 - 10:50, than break]
- [1D small network](eg_1D_small-network.ipynb)
- [1D decaying network](eg_1D_decaying-network.ipynb)
- [1D persistent network](eg_1D_persistent-network.ipynb)
- [1D diverging network](eg_1D_diverging-network.ipynb)
- [1D small-world network](eg_1D_small-world-network.ipynb)
- [1D testing cell models network](eg_1D_testing-cell-models-network.ipynb)
- [1D testing STDP model network](eg_1D_testing-STDP-model-network.ipynb)

## learn-with-exercises [block3, 11:00 - 12:00, than solutions, resume and link with the afternoon]

- [ex_network_A](ex_network_A.ipynb), i.e., a 1D network of 100 cells that receives a sequence of random thalamic inputs
- [ex_network_B](ex_network_B.ipynb), i.e., a 2D network of 900 excitatory cells that receives a sequence of 2D geometric thalamic inputs
- read the material and playing with examples
- resources:
    - SpiNNaker Jupyter Lab login at https://spinn-20.cs.man.ac.uk/hub/home
    - clone or pull the repository https://github.com/albertoarturovergani/CNT-2021
    - go to SpiNNaker directory


## topics for an advanced class
- bio-realistic neural network (i.e, the model)
- large scale computation (i.e., the size)
- model replication (i.e., reproduce results from paper)
- parameters explorations (i.e., optimization algs)
- running parallel simulations (already managed by SpiNNaker, but for NEST or Neuron see http://neuralensemble.org/docs/PyNN/parallel.html) 

## expected take-home-points:

0. import the simulator
1. setup the simulator
2. decide the cell types 
3. design the populations
4. define the synapse types
5. select the connection algorithm
6. make the projections 
7. idealize the stimulus
8. run the simulation
9. save the results
10. recover the results
11. postprocessing (visualization or statistics, etc)
12. close the simulations

# step0: import the simulator

In [1]:
import pyNN.spiNNaker as sim # set accordly also the kernel in the notebook
from pyNN import space 

import numpy as np
import matplotlib.pyplot as plt

# note that if you use nest, import pyNN.nest as sim (see http://neuralensemble.org/docs/PyNN/backends.html)

Detected PyNN version 0.9.4 and Neo version 0.6.1


In [2]:
# sim + tab key to explore PyNN features (classes, modules, functions, instances)

# have a try...

# step1: setup the simulator

In [3]:
sim.setup(
    timestep=1, # [ms]
    min_delay=1, # [ms]
    max_delay=100) # [ms] # not that the max_delay supported by SpiNNaker is timestep * 144

simtime = 200 #ms

2021-04-23 08:14:38 INFO: Read cfg files: /home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spinn_front_end_common/interface/spinnaker.cfg, /home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spynnaker/pyNN/spynnaker.cfg, /home/spinnaker/.spynnaker.cfg
2021-04-23 08:14:38 INFO: Will search these locations for binaries: /home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spinn_front_end_common/common_model_binaries : /home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spynnaker/pyNN/model_binaries
2021-04-23 08:14:38 WARNING: /home/spinnaker/CNT-2021/SpiNNaker/reports has 5 old reports that have not been closed
2021-04-23 08:14:38 WARNING: /home/spinnaker/CNT-2021/SpiNNaker/application_generated_data_files has 6 old reports that have not been closed
2021-04-23 08:14:38 INFO: Setting time scale factor to 1.
2021-04-23 08:14:38 INFO: Setting machine time step to 1000 micro-seconds.


['/home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spinn_front_end_common/interface/spinnaker.cfg', '/home/spinnaker/sPyNNaker/lib/python3.6/site-packages/spynnaker/pyNN/spynnaker.cfg', '/home/spinnaker/.spynnaker.cfg']


# step2: the cell types 

- cell models and source models
- point neuron (mono-compartment model)
- http://neuralensemble.org/docs/PyNN/standardmodels.html

In [4]:
sim.list_standard_models()

['AbstractPyNNModel',
 'IF_cond_exp',
 'IF_curr_exp',
 'IF_curr_alpha',
 'Izhikevich',
 'SpikeSourceArray',
 'SpikeSourcePoisson']

In [5]:
# otherwise see sim.extra_models

sim.extra_models
sim.extra_models.IF_curr_dual_exp
sim.extra_models.IF_curr_exp_sEMD
sim.extra_models.IFCondExpStoc
sim.extra_models.IFCurDelta
sim.extra_models.IFCurrExpCa2Adaptive
sim.extra_models.Izhikevich_cond

spynnaker.pyNN.models.neuron.builds.izk_cond_exp_base.IzkCondExpBase

- example of the different cell spike traces in [eg_1D_testing-cell-models notebook](eg_1D_testing-cell-models.ipynb)

# example with sim.IF_cond_exp 

- Leaky integrate and fire model with fixed threshold and decaying-exponential post-synaptic conductance.
- explicit model https://arxiv.org/pdf/2003.13365.pdf

In [6]:
# parameter names

sim.IF_cond_exp.get_parameter_names()

dict_keys(['tau_m', 'cm', 'v_rest', 'v_reset', 'v_thresh', 'tau_syn_E', 'tau_syn_I', 'tau_refrac', 'i_offset', 'e_rev_E', 'e_rev_I'])

In [7]:
# default parameters

standard_pars = sim.IF_cond_exp.default_parameters

standard_pars

# see parameters of the models http://neuralensemble.org/docs/PyNN/standardmodels.html

{'tau_m': 20.0,
 'cm': 1.0,
 'v_rest': -65.0,
 'v_reset': -65.0,
 'v_thresh': -50.0,
 'tau_syn_E': 5.0,
 'tau_syn_I': 5.0,
 'tau_refrac': 0.1,
 'i_offset': 0.0,
 'e_rev_E': 0.0,
 'e_rev_I': -70.0}

In [8]:
# define your own pars, dictonary of testing parameters

testing_pars = {'tau_m': 20, 
                'cm': 1.0, 
                'v_rest': -65.0, 
                'v_reset': -70.0, 
                'v_thresh': -48.0, 
                'tau_syn_E': 5.0, 
                'tau_syn_I': 5.0, 
                'tau_refrac': 2, 
                'i_offset': 0.0, 
                'e_rev_E': 0.0, 
                'e_rev_I': -70.0}

In [9]:
# initial values

sim.IF_cond_exp().default_initial_values

{'v': -65.0, 'isyn_exc': 0.0, 'isyn_inh': 0.0}

# step3: making cell populations


In [10]:
# define dictionaries

pops = {}
n_cells = {}
neuron_Model = {}
neuron_ModelPars = {}
initial_Values = {}

In [11]:
# define a popolation of excitatory neurons in 1D

popName = 'Exc'
n_cells[popName] = 100
neuron_Model[popName] = sim.IF_cond_exp
neuron_ModelPars[popName] = sim.IF_cond_exp.default_parameters # or standard_pars or testing_pars
initial_Values[popName] = sim.IF_cond_exp.default_initial_values

pops[popName] = sim.Population(n_cells[popName], 
                               neuron_Model[popName],
                               neuron_ModelPars[popName],
                               structure = space.Line(dx=1.0, x0=0.0, y=0.0, z=0.0), 
                               initial_values=None, # e.g, initial_values={'v': sim.RandomDistribution('uniform', (-70.0, -60.0))},
                               label = popName)

pops[popName].record(['spikes','v','gsyn_exc','gsyn_inh'])   

pops

{'Exc': <spynnaker8.models.populations.population.Population at 0x7f18008dca08>}

In [12]:
# define a popolation of inhibitory neurons in 1D

popName = 'Inh'
n_cells[popName] = 100
neuron_Model[popName] = sim.IF_cond_exp
neuron_ModelPars[popName] = sim.IF_cond_exp.default_parameters # or standard_pars or testing_pars
initial_Values[popName] = sim.IF_cond_exp.default_initial_values

pops[popName] = sim.Population(n_cells[popName], 
                              neuron_Model[popName],
                              neuron_ModelPars[popName],
                              structure = space.Line(dx=1.0, x0=0.0, y=0.0, z=0.0),
                              initial_values=None, # e.g, initial_values={'v': sim.RandomDistribution('uniform', (-70.0, -60.0))},
                              label = popName)

pops[popName].record(['spikes','v','gsyn_exc','gsyn_inh'])

pops

{'Exc': <spynnaker8.models.populations.population.Population at 0x7f18008dca08>,
 'Inh': <spynnaker8.models.populations.population.Population at 0x7f18008dcad8>}

In [13]:
# eventually defined random subsets of cells from the the population 

pops['A'] = pops[popName].sample(750) 
pops['B'] = pops[popName].sample(250) 

pops['A'].record(['spikes','v','gsyn_exc','gsyn_inh'])
pops['B'].record(['spikes','v','gsyn_exc','gsyn_inh'])

In [14]:
# some info to define network with 2D or 3D structures

structure = {}

structure['1D'] = space.Line(
                              dx=1.0, 
                              x0=0.0, 
                              y=0.0, 
                              z=0.0),

structure['2D'] = space.Grid2D(
                                aspect_ratio=1.0,
                                dx=1.0,
                                dy=1.0,
                                x0=0.0,
                                y0=0.0,
                                z=0,
                                fill_order='sequential', #'random'
                                rng=None,
                                )

structure['3D'] = space.Grid3D(
                                aspect_ratioXY=1.0,
                                aspect_ratioXZ=1.0,
                                dx=1.0,
                                dy=1.0,
                                dz=1.0,
                                x0=0.0,
                                y0=0.0,
                                z0=0,
                                fill_order='sequential', # 'random'
                                rng=None,
                                )

structure['Sphere'] = space.RandomStructure(
                                            boundary=space.Sphere(radius=100), 
                                            origin=(0.0, 0.0, 0.0), 
                                            rng=None)


structure['Cuboid'] = space.RandomStructure(
                                            boundary=space.Cuboid(
                                                                width=10, 
                                                                height=10, 
                                                                depth=10), 
                                                                origin=(0.0, 0.0, 0.0), 
                                                                rng=None)


# to explore the actual position of the cells:

structure['Cuboid'].generate_positions(1)


array([[ 0.79090446],
       [-0.35930667],
       [-1.43468878]])

In [15]:
# get initial values

pops['Exc'].get_initial_values()

{'v': [-65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0],
 'isyn_exc': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [16]:
pops['Exc'].get_initial_value('v') # voltage

[-65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0, -65.0]

In [17]:
pops['Exc'].get_initial_value('isyn_exc') # excitatory conductance

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [18]:
pops['Exc'].get_initial_value('isyn_inh') # inhibitory conductance

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [19]:
# change initial values, e.g., voltage

pops['Exc'].initialize(v = sim.RandomDistribution('normal', (-65.0, 2.0)))
pops['Exc'].get_initial_value('v') # voltage

[-69.30700726674367, -61.28835338866944, -62.42455490271199, -63.415599075500104, -64.24153762735342, -65.53762473809466, -63.95739548177811, -67.85664016710726, -63.01565018992521, -67.00605745492159, -64.8342272050065, -69.1524576969959, -69.49270123738872, -65.48884133431726, -64.27199117064717, -67.2915840250054, -65.88318172227892, -65.47621463639071, -62.305876575626826, -61.37702211752393, -62.16548641920428, -64.27248232293758, -65.27839940387663, -63.18334976197571, -66.35245397561705, -66.17781472443629, -62.07140473210072, -63.00773982636714, -63.170016175829296, -66.3986840157708, -68.52651390484897, -64.48902039934995, -64.94031087836463, -67.49214155455427, -66.02747404483044, -65.63578396352055, -62.0718761351725, -67.85864131569295, -61.886709795340245, -62.28777207303587, -67.48525552066512, -62.02617699642446, -62.74797874920843, -63.68510222240001, -61.3341171244022, -66.41880003040325, -69.37745038029307, -64.60888118664475, -63.18290261581167, -64.71187297712306, -

In [20]:
# visual check of the custom votlage initial distribution

fig, axes = plt.subplots(1,2, figsize=(7,5))
axes_list = fig.axes

axes_list[0].hist(np.asarray(pops['Exc'].get_initial_value('v')),
                  bins = 50,
                  cumulative = True)

axes_list[0].set_title('CDF of voltage [mV]')

axes_list[1].hist(np.asarray(pops['Exc'].get_initial_value('v')),
                  density = True,
                  bins = 50,
                  cumulative = False)


axes_list[1].set_title('discrete PDF of voltage [mV]')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'discrete PDF of voltage [mV]')

# step4: synapses types (to use with the sim.Projection costructor)

In [21]:
# static synapse weight and delay

weights = np.random.normal(loc=0.04, scale=0.01)
static_synapse = sim.StaticSynapse(weight=weights, delay=0.5) # weights in [uS] and delay in [ms]

# note1: if you use a model with current based synapses, the weights are in nA, otherewise are uS for conductance based synapses models 

In [22]:
# long term / spike-timinig-dependend plasticity (STDP), i.e. learning

stdp_synapse = sim.STDPMechanism(
                                 timing_dependence=sim.SpikePairRule(tau_plus=20.0, tau_minus=20.0, A_plus=0.1, A_minus=0.1),
                                 weight_dependence=sim.AdditiveWeightDependence(w_min=0.0, w_max=1.0),
                                 voltage_dependence=None,
                                 dendritic_delay_fraction=1.0,
                                 weight = 0.05, # initial value
                                 delay = "0.5 + 0.01*d", # distance based delay min_delay + f(distance)
                                 )
# see for details http://neuralensemble.org/docs/PyNN/connections.html#synapse-types

- have a look to [1D testing STDP model network notebook](eg_1D_testing-STDP-model-network.ipynb)

In [23]:
# other learning rules

# sim.extra_models.SpikeNearestPair
# sim.extra_models.PfisterSpikeTripletRule
# sim.extra_models.Vogels2011Rule
# sim.extra_models.RecurrentRule

# info at http://spinnakermanchester.github.io/spynnaker/5.0.0/SPyNNakerModelsAndLimitations.html

# step5: connectors types (to use with the sim.Projection costructor)


In [24]:
# all to all connections

connector = sim.AllToAllConnector(allow_self_connections=True) # autapses=True

In [25]:
# all to all connections with probability

prob = 0.25 # point prob
prob = np.random.normal(loc=0.5, scale=0.1) # distribution of prob
connector = sim.FixedProbabilityConnector(p_connect=prob)

In [26]:
# distance based probability connections

d_rule = "exp(-d)" # or d_expression = "d<5"
connector = sim.DistanceDependentProbabilityConnector(d_expression=d_rule)

In [27]:
# one to one connections

connector = sim.OneToOneConnector()

In [28]:
# fixed number of pre synptic neurons randomly taken link to all pre syn neurons

connector = sim.FixedNumberPreConnector(n = 50, allow_self_connections=True)

In [29]:
# fixed number of post synptic neurons randomly taken link to all post syn neurons

connector = sim.FixedNumberPostConnector(n = 50, allow_self_connections=True)

In [30]:
# small-world connections

do_run = False
if do_run:
    connector = sim.SmallWorldConnector(
                                    degree, # the region length where nodes will be connected locally.
                                    rewiring, # the probability of rewiring each edge.
                                    allow_self_connections=True,
                                    safe=True,
                                    verbose=False,
                                    n_connections=None, # if specified, the number of efferent synaptic connections per neuron.
                                    )


see example [1D small-world network notebook](SpiNNaker/eg_1D_small-world-network)


In [31]:
# CSA Connection Set Algebra costructor ( Djurfeldt 2012 https://pubmed.ncbi.nlm.nih.gov/22437992/)

do_run = False
if do_run:
    #cset = a connection set object
    connector = CSAConnector(cset, safe=True, callback=None)


In [32]:
# from file to connector, i.e., [i, j, weight, delay]

do_run = False
if do_run:
    file = 'yourFile.txt'
    connector = sim.FromFileConnector(
                                    file,
                                    distributed=False,
                                    safe=True,
                                    callback=None,
                                    verbose=False,
                                )

In [33]:
# list based connections, i.e., [i, j, weight, delay]

# one-to-one like list
#            [i, j,  w,   d]
givenList = [[0, 0, 0.08, 1],
             [1, 1, 0.08, 1],
             [2, 2, 0.08, 1],
             [3, 3, 0.08, 1],
             [4, 4, 0.08, 1]]
             #...

connector = sim.FromListConnector(conn_list=givenList)

# powerful tool to draw your own connectivity

## Example of a function to compute a list for the FromListConnector

## e.g., list of Distance based Probability Connections with Distance based Delay (DPCDD)

In [34]:
def compute_DPCDD(n_cells_i, n_cells_j, weights, d_thresh, p_thresh, width): 
    v_c = 0.35 #m/s
    d0 = 1 #ms
    scale = 1
    
    connections = {}
    probabilities = {}
    distances = {}

    connections = []
    probabilities = []
    distances = []
    for pre in range(n_cells_i):
        for post in range(n_cells_j):
            d_ij = np.sqrt((pre - post)**2)
            delay = d0 + d_ij / v_c
            if d_ij > d_thresh: 
                distances.append(d_ij)
                p_ij = scale*np.exp(-0.5 * (d_ij**2/width**2))
                probabilities.append(p_ij)

                if p_ij > p_thresh:
                    connections.append([pre, post, weights, delay])#, [d_ij, p_ij]])

    return connections, distances, probabilities

## operative example: center-surround connections 

In [35]:
# -> see https://link.springer.com/referenceworkentry/10.1007%2F978-1-4614-6675-8_569)
# -> see http://www.scholarpedia.org/article/Neural_inhibition

In [36]:
# define parameters

n_cell = {'excitatory': 100, 'inhibitory': 100}
weights = {'excitatory': 0.008, 'inhibitory': 0.008}
d_thresh = {'excitatory': 0, 'inhibitory': 2} 
p_thresh = {'excitatory': 0.1, 'inhibitory': 0.1}
width = {'excitatory': 1, 'inhibitory': 3}

# ex. look particular cases of one-to-one, all-to-all

In [37]:
connections = {}
distances = {}
probabilities = {}

for synapse_type in ['excitatory', 'inhibitory']:
    connections[synapse_type], distances[synapse_type], probabilities[synapse_type] = compute_DPCDD(
                                                                                                    n_cell[synapse_type], 
                                                                                                    n_cell[synapse_type], 
                                                                                                    weights[synapse_type], 
                                                                                                    d_thresh[synapse_type], 
                                                                                                    p_thresh[synapse_type],
                                                                                                    width[synapse_type])

In [38]:
# visual check

fig, ax = plt.subplots(1,2, figsize=(11,5))
fig.tight_layout(pad=3)
axes_list = fig.axes

axes_list[0].plot(np.asarray(connections['excitatory']).T[0], np.asarray(connections['excitatory']).T[1],'go', label='excitatory')
axes_list[0].plot(np.asarray(connections['inhibitory']).T[0], np.asarray(connections['inhibitory']).T[1],'r+', label='inhibitory')
axes_list[0].grid()
axes_list[0].legend()
axes_list[0].set_title('scatter plot of connections, e.g., cells from')
axes_list[0].set_xlabel('i cells')
axes_list[0].set_ylabel('j cells')
axes_list[0].set_xlim(20,40)
axes_list[0].set_ylim(20,40)


axes_list[1].plot(distances['excitatory'],probabilities['excitatory'],'g+')
axes_list[1].plot(distances['inhibitory'],probabilities['inhibitory'],'r+') 
axes_list[1].plot(np.arange(0, 50), 1*np.exp(-0.5 * (np.arange(0, 50)**2/width['excitatory']**2)), 'g:')
axes_list[1].plot(np.arange(0, 50), 1*np.exp(-0.5 * (np.arange(0, 50)**2/width['inhibitory']**2)), 'r:')
axes_list[1].grid()
axes_list[1].set_xlim(0,15)
axes_list[1].set_ylim(0,1)
axes_list[1].axhline(p_thresh['excitatory'], color='k', label='p_threshold', )
axes_list[1].set_title('probability as function of distance')
axes_list[1].set_xlabel('distance')
axes_list[1].set_ylabel('probability')
axes_list[1].legend()

# Plots show connections with 2 cells local excitation and 4 cells surrounding inhibition, no autapses

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [39]:
# e.g., delay and connectivity

connections['inhibitory'][0:10]

[[0, 3, 0.008, 9.571428571428571],
 [0, 4, 0.008, 12.428571428571429],
 [0, 5, 0.008, 15.285714285714286],
 [0, 6, 0.008, 18.142857142857142],
 [1, 4, 0.008, 9.571428571428571],
 [1, 5, 0.008, 12.428571428571429],
 [1, 6, 0.008, 15.285714285714286],
 [1, 7, 0.008, 18.142857142857142],
 [2, 5, 0.008, 9.571428571428571],
 [2, 6, 0.008, 12.428571428571429]]

# step6: designing projections

In [40]:
# compute manual list of connections to have the 2-4 center-surround structure

weight = {('Exc', 'Exc') : 0.08,
          ('Exc', 'Inh') : 0.08,
          ('Inh', 'Exc') : 0.24
          }

d_thresh = {('Exc', 'Exc'): 0, 
            ('Inh', 'Exc'): 2} 

p_thresh = {('Exc', 'Exc'): 0.1, 
            ('Inh', 'Exc'): 0.1}

width = {('Exc', 'Exc'): 1, 
         ('Inh', 'Exc'): 3}



connections = {}
distances = {}
probabilities = {}

connections['Exc', 'Exc'], distances['Exc', 'Exc'], probabilities['Exc', 'Exc'] = compute_DPCDD(n_cells['Exc'], 
                                                                                                      n_cells['Exc'], 
                                                                                                      weight['Exc', 'Exc'], 
                                                                                                      d_thresh['Exc', 'Exc'], 
                                                                                                      p_thresh['Exc', 'Exc'], 
                                                                                                      width['Exc', 'Exc'])

connections['Inh', 'Exc'], distances['Inh', 'Exc'], probabilities['Inh', 'Exc'] = compute_DPCDD(n_cells['Inh'], 
                                                                                                      n_cells['Exc'], 
                                                                                                      weight['Inh', 'Exc'], 
                                                                                                      d_thresh['Inh', 'Exc'], 
                                                                                                      p_thresh['Inh', 'Exc'], 
                                                                                                      width['Inh', 'Exc'])

In [41]:
# make the projections (costructor links within and between populations)

proj = {}



proj['Exc', 'Exc'] = sim.Projection(pops['Exc'], 
                                    pops['Exc'],
                                    connector = sim.FromListConnector(connections['Exc', 'Exc']),
                                    synapse_type = None,
                                    receptor_type = 'excitatory',
                                    space = space.Space(axes = 'x'),
                                    label = 'exc-exc connections'
                                    )

proj['Exc', 'Inh'] = sim.Projection(pops['Exc'], pops['Inh'],
                                    connector = sim.OneToOneConnector(), 
                                    synapse_type = sim.StaticSynapse(weight=weight['Exc', 'Inh'], delay=1), 
                                    receptor_type = 'excitatory',
                                    space = space.Space(axes = 'x'),
                                    label = 'exc-inh connections'
                                    )


proj['Inh', 'Exc'] = sim.Projection(pops['Inh'], pops['Exc'],
                                    connector = sim.FromListConnector(connections['Inh', 'Exc']),
                                    synapse_type = None,
                                    receptor_type = 'inhibitory',
                                    space = space.Space(axes = 'x'),
                                    label = 'inh-exc connections'
                                    )

# note that using the FromListConnector is not necessary set the synapse weights and delays because are already define inside

# they have to be defined with other constructors (OneToOne, AllToAll, etc)

In [42]:
# note for the the space arg with 2 or 3 dimensions

"""
pops[popName] = sim.Population(n_cells[popName], 
                               neuron_Model[popName],
                               neuron_ModelPars[popName],
                               structure = space.Line(dx=1.0, x0=0.0, y=0.0, z=0.0), 
                               initial_values=None, # e.g, initial_values={'v': sim.RandomDistribution('uniform', (-70.0, -60.0))},
                               label = popName)

"""


s = {}
s['1D'] = space.Space(axes = 'x')
s['2D'] = space.Space(axes = 'xy')
s['3D'] = space.Space(axes = 'xyz')
s['Sphere'] = space.Space(axes = 'xyz')
s['Cuboid'] = space.Space(axes = 'xyz')


# step7: setting the stimulus

In [43]:
# define the list of spike sources, e.g, with a gaussian input around 100 [ms]

popName = 'Thalamus'  

n_cells[popName] = n_cells['Exc']
spike_times = [[]]*n_cells[popName] #list of spike lists, where one spike list is related to one spike source

# randomly select the id source
random_sources_idx = [np.random.randint(n_cells[popName]*0.45, n_cells[popName]*0.55) for i in range(n_cells[popName])]

# randomly assign for each id source a sequence of spike times, i.e., when the cell spikes
for idx, sources in enumerate(random_sources_idx):
    spike_times[sources] = np.sort([np.random.normal(loc=100, scale=10) for n in range(5)])

spike_times
%matplotlib
a = plt.eventplot(spike_times)
plt.xlabel('[ms]')
plt.ylabel('Thalamic cells')
plt.title('Raster plot of input spike sources')
plt.xlim(0, simtime)

spike_times[40:60]

Using matplotlib backend: module://ipympl.backend_nbagg


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[],
 [],
 [],
 [],
 [],
 array([ 88.051998  ,  95.01461395,  95.52116749,  97.76671324,
        119.53608144]),
 array([ 90.41289497,  91.30919298,  93.96675837, 107.09326122,
        110.18229996]),
 array([ 86.73085611,  96.42366934, 100.24089977, 102.11634561,
        103.50275302]),
 array([ 89.40142883,  97.00599926,  97.8731655 , 109.09095583,
        113.19139636]),
 array([ 86.96367352,  94.59880657,  99.6017602 , 103.02191736,
        105.04491577]),
 array([ 94.25480799, 105.74248359, 107.81701358, 113.14202357,
        114.65353972]),
 array([ 94.17465694,  95.50105541,  97.5789795 ,  99.90944493,
        100.25917887]),
 array([ 86.26638684,  92.29360038, 100.80186529, 101.16403911,
        111.30133635]),
 array([100.57231202, 103.83464287, 104.35937559, 105.11200719,
        105.21525853]),
 array([ 83.47692986,  98.28369815, 103.87255682, 106.69830097,
        120.87435218]),
 [],
 [],
 [],
 [],
 []]

In [44]:
# define the spike sources populations and projections

neuron_Model[popName] = sim.SpikeSourceArray(spike_times=spike_times)

pops[popName] = sim.Population(n_cells[popName], 
                               neuron_Model[popName],
                               label = popName)
                              # add spatial constraint
    
proj['Thalamus', 'Exc'] = sim.Projection(pops['Thalamus'], pops['Exc'],
                                           connector = sim.OneToOneConnector(),
                                           synapse_type = sim.StaticSynapse(weight=0.08, delay=1),
                                           receptor_type = 'excitatory',
                                            #space=<pyNN.space.Space object at 0x7ff8f25a2110>,
                                           label = 'thalamus-exc connections'
                                            )


In [45]:
# otherwise define a spike sources from poisson process

do_run = False

if do_run:
    neuron_Model[popName] = sim.SpikeSourcePoisson(
                                                rate=50.0, # [Hz]
                                                start=100, 
                                                duration=None)

    pops[popName] = sim.Population(n_cells[popName], 
                                   neuron_Model[popName],
                                   label = popName)
                                  # add spatial constraint

    proj['Thalamus', 'Exc'] = sim.Projection(pops['Thalamus'], pops['Exc'],
                   connector = sim.OneToOneConnector(),
                   synapse_type = sim.StaticSynapse(weight=0.08, delay=1),
                   receptor_type = 'excitatory',
                    #space=<pyNN.space.Space object at 0x7ff8f25a2110>,
                   label = 'thalamus-exc connections'
                    )


# step8: run simulation

In [46]:
sim.run(simtime) # time_bins=200 [ms]

# brief recap, what we are going to run:
# - a network with two pops of 100 exc and 100 inh cells
# - connections are center-surround
# - thalamic input is a sequence of gussian spikes around 100ms

# wait some minuts...

2021-04-23 08:14:58 INFO: Simulating for 200 1.0ms timesteps using a hardware timestep of 1000us
2021-04-23 08:14:58 INFO: Starting execution process
2021-04-23 08:15:01 INFO: Time 0:00:03.123142 taken by SpallocMaxMachineGenerator
Pre allocating resources for Extra Monitor support vertices
|0%                          50%                         100%|
2021-04-23 08:15:10 INFO: Time 0:00:08.756716 taken by PreAllocateResourcesForExtraMonitorSupport
Partitioning graph vertices
|0%                          50%                         100%|
Partitioning graph edges
|0%                          50%                         100%|
2021-04-23 08:15:14 INFO: Time 0:00:04.862318 taken by PartitionAndPlacePartitioner
Created spalloc job 5963843
2021-04-23 08:15:14 INFO: Created spalloc job 5963843
Waiting for board power commands to complete.
2021-04-23 08:15:15 INFO: Waiting for board power commands to complete.
2021-04-23 08:15:19 INFO: Time 0:00:05.045141 taken by SpallocAllocator
2021-04-23 0

200.0

# step9: save results

In [47]:
outputs = {}

for layer in ['Exc', 'Inh']:
    
    # save on the notebook space
    outputs[layer] = pops[layer].get_data()
    
    # save in the folder space
    for recording in ['v', 'gsyn_inh', 'gsyn_exc', 'spikes']:
        pops[layer].write_data(str(layer) + '_' + str(recording) + '.pkl')
        

Getting spikes for Exc
|0%                          50%                         100%|
Getting v for Exc
|0%                          50%                         100%|
Getting gsyn_exc for Exc
|0%                          50%                         100%|
Getting gsyn_inh for Exc
|0%                          50%                         100%|
Getting spikes for Exc
|0%                          50%                         100%|
Getting v for Exc
|0%                          50%                         100%|
Getting gsyn_exc for Exc
|0%                          50%                         100%|
Getting gsyn_inh for Exc
|0%                          50%                         100%|
Getting spikes for Exc
|0%                          50%                         100%|
Getting v for Exc
|0%                          50%                         100%|
Getting gsyn_exc for Exc
|0%                          50%                         100%|
Getting gsyn_inh for Exc
|0%                          50%  

# step10: recover results

In [48]:
def recover_results(outputs):
    results = {}
    for key in outputs.keys(): # to extract the name of the layer, e.g., Exc, Inh, Thalamus, etc  
        
        # to get voltage and conductances
        for analogsignal in outputs[key].segments[0].analogsignals:
            print(key, analogsignal.name)
            results[key, analogsignal.name] = analogsignal

        # to get spikes
        results[key, 'spikes'] = outputs[key].segments[0].spiketrains
    return results

In [49]:
# check results

results = recover_results(outputs)
results.keys()

Exc v
Exc gsyn_exc
Exc gsyn_inh
Inh v
Inh gsyn_exc
Inh gsyn_inh


dict_keys([('Exc', 'v'), ('Exc', 'gsyn_exc'), ('Exc', 'gsyn_inh'), ('Exc', 'spikes'), ('Inh', 'v'), ('Inh', 'gsyn_exc'), ('Inh', 'gsyn_inh'), ('Inh', 'spikes')])

# step11: postprocessing (looking the results)

In [50]:
# eventually import pkl files

do_run = False

if do_run:
    import pickle
    
    # e.g., 
    with open('Exc_v.pkl', 'rb') as f:
            data = pickle.load(f)


In [51]:
# check the spikes

fig, axes = plt.subplots(1, 1)
fig.tight_layout(pad=5)
axes_list = fig.axes

for idx, value in enumerate(['Exc']):
    axes_list[idx].eventplot(results[value, 'spikes'])
    axes_list[idx].eventplot(spike_times, color='r')
    axes_list[idx].set_title('rasterplot of ' + str(value) + ' layer')
    axes_list[idx].set_xlabel('[ms]')
    axes_list[idx].set_ylabel('cells')
    axes_list[idx].legend()

    
fig, axes = plt.subplots(1, 1)
fig.tight_layout(pad=5)
axes_list = fig.axes

for idx, value in enumerate(['Inh']):
    axes_list[idx].eventplot(results[value, 'spikes'])
    axes_list[idx].eventplot(spike_times, color='r')
    axes_list[idx].set_title('rasterplot of ' + str(value) + ' layer')
    axes_list[idx].set_xlabel('[ms]')
    axes_list[idx].set_ylabel('cells')

    
# in red the spikes from the sources

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

2021-04-23 08:16:52 WARNING: No handles with labels found to put in legend.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [52]:
# check the voltage

fig, axes = plt.subplots(1, 1)#, sharex=True)
fig.tight_layout(pad=4)
axes_list = fig.axes
for idx, value in enumerate(['Exc']):
    im = axes_list[idx].imshow(results[value, 'v'].T)
    axes_list[idx].set_title('voltage of ' + str(value) + ' layer')
    axes_list[idx].set_xlabel('time [ms]')
    axes_list[idx].set_ylabel('cells')
    fig.colorbar(im, ax=axes_list[idx], fraction=0.010, label='[mV]')
    
fig, axes = plt.subplots(1, 1)#, sharex=True)
fig.tight_layout(pad=4)
axes_list = fig.axes
for idx, value in enumerate(['Inh']):
    im = axes_list[idx].imshow(results[value, 'v'].T)
    axes_list[idx].set_title('voltage of ' + str(value) + ' layer')
    axes_list[idx].set_xlabel('time [ms]')
    axes_list[idx].set_ylabel('cells')
    fig.colorbar(im, ax=axes_list[idx], fraction=0.010, label='[mV]')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [53]:
# check the conductances

for layer in ['Exc', 'Inh']:
    fig, axes = plt.subplots(1, 1)#, figsize=(9,5))
    fig.tight_layout(pad=4)
    fig.suptitle(str(layer) + ' layer')
    axes_list = fig.axes
    
    for idx, gsyn in enumerate(['gsyn_exc']):#, 'gsyn_inh']):
        im = axes_list[idx].imshow(results[layer, gsyn].T)
        axes_list[idx].set_title(str(gsyn))
        axes_list[idx].set_xlabel('time [ms]')
        axes_list[idx].set_ylabel('cells')
        fig.colorbar(im, ax=axes_list[idx], fraction=0.010, label='[uS]')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

# step12: close simulation


In [54]:
sim.end()

# learn-by-examples [block2, 10:25 - 12:00]

- [1D entry network](eg_1D_entry-network.ipynb)
- [1D testing cell models network](eg_1D_testing-cell-models-network.ipynb)
- [1D testing STDP model network](eg_1D_testing-STDP-model-network.ipynb)
- [1D small-world network](eg_1D_small-world-network.ipynb)
- [1D decaying network](eg_1D_decaying-network.ipynb)
- [1D persistent network](eg_1D_persistent-network.ipynb)
- [1D diverging network](eg_1D_diverging-network.ipynb)





# learn-with-exercices and resume with link for the afternoon [block3, 12:00 - 12:30]

- [ex_network_A](ex_network_A.ipynb), i.e., a 1D network of 100 cells that receives a sequence of random thalamic inputs
- [ex_network_B](ex_network_B.ipynb), i.e., a 2D network of 900 excitatory cells that receives a sequence of 2D geometric thalamic inputs
- read the material and playing with examples
- resources:
    - SpiNNaker Jupyter Lab login at https://spinn-20.cs.man.ac.uk/hub/home
    - clone repository https://github.com/albertoarturovergani/CNT-2021
    - SpiNNaker


# learn-from-scretch
- create equivalent or extended PyNN functions by using numpy, e.g., specially for peculiar type of connectivities (use FromListConnector)
- create a network and check the [balance]( http://www.scholarpedia.org/article/Balance_of_excitation_and_inhibition) between excitatory and inhibitory components  (e.g. [Brette et al 2007](http://neuralensemble.org/docs/PyNN/examples/VAbenchmarks.html))
- explore boundary conditions in 1D by comparing open and close ring networks (define properly the list of connections)
- compare two populations of different cell models and observe their difference on reacting to a stimulus
- create a network to make a deep signal processing with statistics, data analysis, and exploration of the frequency domain (FFT, HHT)
- design a set of stimuli with different onset timing and shape and test them on a simple network
- take one [example](http://neuralensemble.org/docs/PyNN/examples.html) from the PyNN website made for NEST and adapt to run on SpiNNaker
- take one example from the learn-by-examples section and extend it in 2D or 3D  
- use the notebook called [eg_nD_blank_network](eg_nD_blank-network.ipynb) and start your personal simulations


